config/routes.rb
Rails.application.routes.draw do

  root :to => 'splash#index'

	resources :portfolio, path: '/my-team/'
	resources :ranking, path: '/rankings/'
	
	resources :home, path: '/match-ups/'
	
	resources :stats, except: [:destroy] do
		collection { post :import }
		collection { delete :kill }
	end
	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
 		if params[:firstTeam].present? && params[:secondTeam].present?
 			#return team1 + team2 search + names
 			@team1 = Stat.search(params[:firstTeam]) 	
 			@team2 = Stat.search(params[:secondTeam])
 			@team1name = @team1.uniq.pluck("team1")
 			@team2name = @team2.uniq.pluck("team1") 			
 

			#objects to be called by others
 			@all = Stat.all
 			@team1wk = @team1.order("week").uniq.pluck("week")
 			@week = Stat.pluck("week").last
 			@year = Stat.pluck("year").last

			#return most recent table values for team1 + team2 in array
 			@statArrayTeam1 = @team1.where("year = ?", @year).pluck("year", "week", "win", "team2", "team1pts", "team2pts", "id", "url")
 			@team1CurrentStat = @statArrayTeam1.to_a
 			@statArrayTeam2 = @team2.where("year = ?", @year).pluck("year", "week", "win", "team2", "team1pts", "team2pts", "id", "url")
 			@team2CurrentStat = @statArrayTeam2.to_a
 			
			#return team1 + team2 data arrays
 			@team1gt = @team1.where("year = ?", @year).pluck("win", "GameMean")
 			@team2gt = @team2.where("year = ?", @year).pluck("win", "GameMean")			
 			@team1off = @team1.where("year = ?", @year).pluck("win", "OFFGameMean")
 			@team2off = @team2.where("year = ?", @year).pluck("win", "OFFGameMean")
 			@team1def = @team1.where("year = ?", @year).pluck("win", "DEFGameMean")
 			@team2def = @team2.where("year = ?", @year).pluck("win", "DEFGameMean")
 			@team1offVal = @team1.where("year = ?", @year).pluck("OFFGameMean")
 			@team2offVal = @team2.where("year = ?", @year).pluck("OFFGameMean")
 			@team1defVal = @team1.where("year = ?", @year).pluck("DEFGameMean")
 			@team2defVal = @team2.where("year = ?", @year).pluck("DEFGameMean")	
 			@team1s2dm = @team1.where("year = ?", @year).pluck("Season2dateMean")
 			@team2s2dm = @team2.where("year = ?", @year).pluck("Season2dateMean")
 			
 			#return last value for team1 + team2	
 			@teamValue1 = @team1.where("year = ?", @year).pluck("Season2dateMean", "Season2dateOFFMean", "Season2dateDEFMean").last
 			@teamValue2 = @team2.where("year = ?", @year).pluck("Season2dateMean", "Season2dateOFFMean", "Season2dateDEFMean").last
			@team1current = @team1.where("year = ?", @year).pluck("CurrentMeanTrend").last
 			@team2current = @team2.where("year = ?", @year).pluck("CurrentMeanTrend").last
 
 			#return current season2date values by team
 				@teamOrder = @all.group("id", "team1").order("team1")
 				@currentData = @teamOrder.where("week = ?", @week).where("year = ?", @year)
 			@teamValues = @currentData.pluck("Season2dateMean", "Season2dateOFFMean", "Season2dateDEFMean")

 		end
 		@teamNames = Stat.order(:team1).uniq.pluck(:team1)
 		@stats = Stat.all
	else
	end
	
	def show
		@stat = Stat.find(params[:id])
	end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_chartScript.html.erb
<script type="text/javascript">
	$(function () {
		var gameResultTeam1 = <%= raw @team1gt.to_json %>
		var gameResultTeam2 = <%= raw @team2gt.to_json %>
		var gameOFFTeam1 = <%= raw @team1off.to_json %>
		var gameOFFTeam2 = <%= raw @team2off.to_json %>
		var gameDEFTeam1 = <%= raw @team1def.to_json %>
		var gameDEFTeam2 = <%= raw @team2def.to_json %>
		var chart = new Highcharts.Chart({
		chart: {
			renderTo: 'chart',
			type: 'line',
			fontSize:'100%',
			backgroundColor:'rgba(255, 255, 255, 0.1)'
		},
		title: {
			text: '<%= @team1name.first.gsub('"','') %> vs <%= @team2name.first.gsub('"','') %>',
			style: {
				fontSize:'2vmax'
			}
		},
		subtitle: {
			text: 'Game-Q By Week',
			style: {
				fontSize:'1.7vmax'
			}
		},
		xAxis: {
			categories: <%= @team1wk  %>,
			title: {
				style: {
                    fontSize:'1.7vmax',
                }
			}
		},
		yAxis: {
			title: {
				text: '',
				style: {
                    fontSize:'1.7vmax',
                }
			}
		},
		plotOptions: {
			line: {
				dataLabels: {
					enabled: false,
				},
				enableMouseTracking: true
			}
		},
		series: [{
			name: '<%= @team1name.first.gsub('"','') %>',
			color: '#006E29',
			data: gameResultTeam1
		}, {
			name: '<%= @team2name.first.gsub('"','') %>',
			color: '#333333',
			data: gameResultTeam2
		}]
	});
		$(".transform").change(function() {
			var value = this.getAttribute("value");

			if (value == 'a') 
			{
				chart.series[0].remove();
				chart.series[0].remove();
				chart.setTitle({ 
					text: '<%= @team1name.first.gsub('"','') %> (<%= @team1s2dm.last.round(3) %>) vs <%= @team2name.first.gsub('"','') %> (<%= @team2s2dm.last.round(3) %>)' 
					}, 
					{ 
					text: 'Game-Q By Week'
				});
				chart.addSeries({
					name: '<%= @team1name.first.gsub('"','') %>',
					type: 'line',
					color: '#006E29',  
				    data: gameResultTeam1             
				});   
				chart.addSeries({
					name: '<%= @team2name.first.gsub('"','') %>',
					type: 'line',
					color: '#333333',  
				    data: gameResultTeam2              
				});  
			}


			else if (value == 'b') 
			{
				chart.series[0].remove();
				chart.series[0].remove();
				chart.setTitle({ 
					text: '<%= @team1name.first.gsub('"','') %> (<%= @team1offVal.last.round(3) %>) vs <%= @team2name.first.gsub('"','') %> (<%= @team2offVal.last.round(3) %>)' 
					}, 
					{ 
					text: 'Game-Q By Week'
				});
				chart.addSeries({
					name: '<%= @team1name.first.gsub('"','') %>',
					type: 'line',
					color: '#006E29',  
					data: gameOFFTeam1              
				});   
				chart.addSeries({
					name: '<%= @team2name.first.gsub('"','') %>',
					type: 'line',
					color: '#333333',  
					data: gameOFFTeam2              
				});  
			}

			else if (value == 'c') 
			{
				chart.series[0].remove();
				chart.series[0].remove();
				chart.setTitle({ 
					text: '<%= @team1name.first.gsub('"','') %> (<%= @team1defVal.last.round(3) %>) vs <%= @team2name.first.gsub('"','') %> (<%= @team2defVal.last.round(3) %>)' 
					}, 
					{ 
					text: 'Game-Q By Week'
				});
				chart.addSeries({
					name: '<%= @team1name.first.gsub('"','') %>',
					type: 'line',
					color: '#006E29',  
				    data: gameDEFTeam1             
				});   
				chart.addSeries({
					name: '<%= @team2name.first.gsub('"','') %>',
					type: 'line',
					color: '#333333',  
				    data: gameDEFTeam2             
				});  
			}

			else {
			   alert("Error!");   
			}
		});
	});
</script>

app/views/home/_columnScript.html.erb
<script type="text/javascript">
$(function () {
    $('#column').highcharts({
        chart: {
            type: 'column',
			backgroundColor:'rgba(255, 255, 255, 0.1)'
        },
        title: {
            text: '',
        },
		xAxis: {
			categories: ['Team', 'Offense', 'Defense']
		},
		yAxis: {
			title: {
				text: 'Season-Q',
				style: {
                    fontSize:'1.7vmax',
                }
			}
		},
        series: [{
            name: '<%= @team1name.first.gsub('"','') %>',
            data: <%= @teamValue1 %>,
            color: '#006E29'
        }, {
            name: '<%= @team2name.first.gsub('"','') %>',
            data: <%= @teamValue2 %>,
            color: '#333333'
        }]
    });
});
</script>

app/views/home/_scatterScript.html.erb
<% a = @teamValues %>
<% b = @teamNames %>
<% c = @team1current %>
<% if c < -201 %>
	<% c1 = 5 %>
<% elsif c < -160 %>
	<% c1 = 8 %>
<% elsif c < -136 %>
	<% c1 = 10 %>
<% elsif c < -32 %>
	<% c1 = 13 %>
<% elsif c < 0 %>
	<% c1 = 15 %>
<% elsif c < 32 %>
	<% c1 = 25 %>
<% elsif c < 104 %>
	<% c1 = 30 %>
<% elsif c < 136 %>
	<% c1 = 35 %>
<% elsif c < 160  %>
	<% c1 = 38 %>
<% elsif c < 201  %>
	<% c1 = 40 %>
<% else %>
	<% c1 = 50 %>
<% end %>

<% d = @team2current %>
<% if d < -201 %>
	<% d1 = 5 %>
<% elsif d < -160 %>
	<% d1 = 8 %>
<% elsif d < -136 %>
	<% d1 = 10 %>
<% elsif d < -32 %>
	<% d1 = 13 %>
<% elsif d < 0 %>
	<% d1 = 15 %>
<% elsif d < 32 %>
	<% d1 = 25 %>
<% elsif d < 104 %>
	<% d1 = 30 %>
<% elsif d < 136 %>
	<% d1 = 35 %>
<% elsif d < 160  %>
	<% d1 = 38 %>
<% elsif d < 201  %>
	<% d1 = 40 %>
<% else %>
	<% d1 = 50 %>
<% end %>

<script type="text/javascript">
$(function () {

    // Give the points a 3D feel by adding a radial gradient
    Highcharts.getOptions().colors = $.map(Highcharts.getOptions().colors, function (color) {
        return {
            radialGradient: {
                cx: 0.4,
                cy: 0.3,
                r: 0.5
            },
            stops: [
                [0, color],
                [1, Highcharts.Color(color).brighten(-0.2).get('rgb')]
            ]
        };
    });

    // Set up the chart
    var chart = new Highcharts.Chart({
        chart: {
            renderTo: 'scatter',
            margin: 100,
            type: 'scatter',
			backgroundColor:'rgba(255, 255, 255, 0.1)',
            options3d: {
                enabled: true,
                alpha: 5,
                beta: 5,
                depth: 200,
                viewDistance: 5,

                frame: {
                    bottom: { size: 1, color: 'rgba(0,0,0,0.02)' },
                    back: { size: 1, color: 'rgba(0,0,0,0.03)' },
                    side: { size: 1, color: 'rgba(0,0,0,0.04)' }
                }
            }
        },
        title: {
            text: 'Season-Q',
            style: {
				fontSize:'2vmax'
			}
        },
		xAxis: {
			title: {
				text: 'TEAM'
			}
		},  
		yAxis: {
			title: {
				text: 'OFFENSE'
			}
		}, 
		zAxis: {
			title: {
				text: 'DEFENSE'
			}
		},  
        plotOptions: {
            scatter: {
                width: 10,
                height: 10,
                depth: 10
            }
        },
        tooltip: {
            formatter: function() {return ' ' +
                this.series.name + '<br />' +
                'TM: ' + this.point.x + '<br />' +
                'OFF: ' + this.point.y + '<br />' +
                'DEF: ' + this.point.z;
            }
        },
        legend: {
            enabled: false
        },

        series: [{            
            name: '<%= @team1name.first.gsub('"','') %>',
            data: [<%= @teamValue1 %>],
            color: '#006E29',
            marker: {
                symbol: 'circle',
                radius: <%= c1 %>
            },
        }, {          
            name: '<%= @team2name.first.gsub('"','') %>',
            data: [<%= @teamValue2 %>],
            color: '#333333',
            marker: {
                symbol: 'circle',
                radius: <%= d1 %>
            },
        }, {  
        	name: '<%= b[0] %>',
            data: [<%= a[0] %>],
            color: '#dd402e',
            marker: {
                symbol: 'circle'
            },
        }, {      
        	name: '<%= b[1] %>',
            data: [<%= a[1] %>],
            color: '#dd402e',
            marker: {
                symbol: 'circle'
            },
        }, {        
        	name: '<%= b[2] %>',
            data: [<%= a[2] %>],
            color: '#dd402e',
            marker: {
                symbol: 'circle'
            },
        }, {        
        	name: '<%= b[3] %>',
            data: [<%= a[3] %>],
            color: '#dd402e',
            marker: {
                symbol: 'circle'
            },
        }, {        
        	name: '<%= b[4] %>',
            data: [<%= a[4] %>],
            color: '#dd402e',
            marker: {
                symbol: 'circle'
            },
        }, {           
        	name: '<%= b[5] %>',
            data: [<%= a[5] %>],
            color: '#dd402e',
            marker: {
                symbol: 'circle'
            },
        }, {          
        	name: '<%= b[6] %>',
            data: [<%= a[6] %>],
            color: '#dd402e',
            marker: {
                symbol: 'circle'
            },
        }, {       
        	name: '<%= b[7] %>',
            data: [<%= a[7] %>],
            color: '#dd402e',
            marker: {
                symbol: 'circle'
            },
        }, {     
        	name: '<%= b[8] %>',
            data: [<%= a[8] %>],
            color: '#dd402e',
            marker: {
                symbol: 'circle'
            },
        }, {     
        	name: '<%= b[9] %>',
            data: [<%= a[9] %>],
            color: '#dd402e',
            marker: {
                symbol: 'circle'
            },
        }, {     
        	name: '<%= b[10] %>',
            data: [<%= a[10] %>],
            color: '#dd402e',
            marker: {
                symbol: 'circle'
            },
        }, {   
        	name: '<%= b[11] %>',
            data: [<%= a[11] %>],
            color: '#dd402e',
            marker: {
                symbol: 'circle'
            },
        }, {            
        	name: '<%= b[12] %>',
            data: [<%= a[12] %>],
            color: '#dd402e',
            marker: {
                symbol: 'circle'
            },
        }, {            
        	name: '<%= b[13] %>',
            data: [<%= a[13] %>],
            color: '#dd402e',
            marker: {
                symbol: 'circle'
            },
        }, {             
        	name: '<%= b[14] %>',
            data: [<%= a[14] %>],
            color: '#dd402e',
            marker: {
                symbol: 'circle'
            },
        }, {   
        	name: '<%= b[15] %>',
            data: [<%= a[15] %>],
            color: '#dd402e',
            marker: {
                symbol: 'circle'
            },
        }, {   
        	name: '<%= b[16] %>',
            data: [<%= a[16] %>],
            color: '#dd402e',
            marker: {
                symbol: 'circle'
            },
        }, {       
        	name: '<%= b[17] %>',
            data: [<%= a[17] %>],
            color: '#dd402e',
            marker: {
                symbol: 'circle'
            },
        }, {       
        	name: '<%= b[18] %>',
            data: [<%= a[18] %>],
            color: '#dd402e',
            marker: {
                symbol: 'circle'
            },
        }, {     
        	name: '<%= b[19] %>',
            data: [<%= a[19] %>],
            color: '#dd402e',
            marker: {
                symbol: 'circle'
            },
        }, {    
        	name: '<%= b[20] %>',
            data: [<%= a[20] %>],
            color: '#dd402e',
            marker: {
                symbol: 'circle'
            },
        }, {          
        	name: '<%= b[21] %>',
            data: [<%= a[21] %>],
            color: '#dd402e',
            marker: {
                symbol: 'circle'
            },
        }, {             
        	name: '<%= b[22] %>',
            data: [<%= a[22] %>],
            color: '#dd402e',
            marker: {
                symbol: 'circle'
            },
        }, {          
        	name: '<%= b[23] %>',
            data: [<%= a[23] %>],
            color: '#dd402e',
            marker: {
                symbol: 'circle'
            },
        }, {             
        	name: '<%= b[24] %>',
            data: [<%= a[24] %>],
            color: '#dd402e',
            marker: {
                symbol: 'circle'
            },
        }, {           
        	name: '<%= b[25] %>',
            data: [<%= a[25] %>],
            color: '#dd402e',
            marker: {
                symbol: 'circle'
            },
        }, {          
        	name: '<%= b[26] %>',
            data: [<%= a[26] %>],
            color: '#dd402e',
            marker: {
                symbol: 'circle'
            },
        }, {           
        	name: '<%= b[27] %>',
            data: [<%= a[27] %>],
            color: '#dd402e',
            marker: {
                symbol: 'circle'
            },
        }, {           
        	name: '<%= b[28] %>',
            data: [<%= a[28] %>],
            color: '#dd402e',
            marker: {
                symbol: 'circle'
            },
        }, {         
        	name: '<%= b[29] %>',
            data: [<%= a[29] %>],
            color: '#dd402e',
            marker: {
                symbol: 'circle'
            },
        }, {         
        	name: '<%= b[30] %>',
            data: [<%= a[30] %>],
            color: '#dd402e',
            marker: {
                symbol: 'circle'
            },
        }, {          
        	name: '<%= b[31] %>',
            data: [<%= a[31] %>],
            color: '#dd402e',
            marker: {
                symbol: 'circle'
            },
        }]
    });

    // Add mouse events for rotation
    $(chart.container).bind('mousedown.hc touchstart.hc', function (e) {
        e = chart.pointer.normalize(e);

        var posX = e.pageX,
            posY = e.pageY,
            alpha = chart.options.chart.options3d.alpha,
            beta = chart.options.chart.options3d.beta,
            newAlpha,
            newBeta,
            sensitivity = 5; // lower is more sensitive

        $(document).bind({
            'mousemove.hc touchdrag.hc': function (e) {
                // Run beta
                newBeta = beta + (posX - e.pageX) / sensitivity;
                chart.options.chart.options3d.beta = newBeta;

                // Run alpha
                newAlpha = alpha + (e.pageY - posY) / sensitivity;
                chart.options.chart.options3d.alpha = newAlpha;

                chart.redraw(false);
            },
            'mouseup touchend': function () {
                $(document).unbind('.hc');
            }
        });
    });

});
</script>

app/views/home/index.html.erb
<title>Match-Ups | The Q5</title>
<div class="x-container max width">
	<div class="x-landmark-breadcrumbs-wrap">
		<div class="x-landmark">
			<h1 class="h-landmark entry-title"><span>Match-Ups</span></h1>
			<%= link_to root_path do %><p><i>Want to Learn More About This Tool?</i></p><% end %>
		</div>
	</div>
</div>
<% if params[:firstTeam].present? && params[:secondTeam].present? %>	
	<%= render partial: 'chartScript' %>
	<%= render partial: 'columnScript' %>
	<%= render partial: 'scatterScript' %>
	<div id="chart"></div>
	<div id="transform">
		<input class="transform" name="newSeries" type="radio" value="a"> Team</input>
		<input class="transform" name="newSeries" type="radio" value="b"> Offense</input>
		<input class="transform" name="newSeries" type="radio" value="c"> Defense</input>
	</div>
	<div id="teamTable">
		<div id="team1Table">	
			<table cellspacing='0'> 
				<thead>
					<tr>
						<th colspan="3"><%= @team1name.first %></th>
					</tr>
				</thead>
				<tbody>
					<% @team1CurrentStat.each do |t1| %>
						<% if t1[5].nil? %>
						<tr>
							<td><i>Wk <%= t1[1] %></i>:</td>
							<td ><b><%= t1[2] %></b></td>
							<td></td>
						</tr>	
						<% else %>
						<tr>
							<td><i>Wk <%= t1[1] %></i>:</td>	
							<td><b><%= t1[2] %></b> <%= t1[4] %>-<%= t1[5] %> vs <%= t1[3] %></td>
							<td><%= link_to 'Game Map', home_path(:id => t1[6]) %></td>
						</tr>					
						<% end %>
					<% end %>
				</tbody>
			</table>
		</div>
		<div id="team2Table">	  
			<table cellspacing='0'> 
				<thead>
					<tr>
						<th colspan="3"><%= @team2name.first %></th>
					</tr>
				</thead>
				<tbody>
					<% @team2CurrentStat.each do |t2| %>
						<% if t2[5].nil? %>
						<tr>
							<td><i>Wk <%= t2[1] %></i>:</td>
							<td><b><%= t2[2] %></b></td>
							<td></td>
						</tr>	
						<% else %>
						<tr>
							<td><i>Wk <%= t2[1] %></i>:</td>
							<td><b><%= t2[2] %></b> <%= t2[4] %>-<%= t2[5] %> vs <%= t2[3] %></td>
							<td><%= link_to 'Game Map', home_path(:id => t2[6]) %></td>
						</tr>					
						<% end %>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
	<br style="clear:both" />
	<div id="column"></div>
	<div id="scatter" style="padding-top: 35px;"></div>
	<p class="newMatch">
		<%= link_to 'Matchup', home_index_path, class: 'a' %>
	</p>
	
<% else %>
	<div id="teamMatchup">
		<h2>
			Match-Ups
		</h2>
		<%= form_tag(home_index_path, :method => "get", id: "search-form", :validate=>true) do %>
			<%= select_tag :firstTeam, options_for_select(@teamNames, params[:firstTeam]), :prompt => 'Select Team 1' %><i> VS </i>
			<%= select_tag :secondTeam, options_for_select(@teamNames, params[:secondTeam]), :prompt => 'Select Team 2' %><br /><br /><br />
			<%= submit_tag "Match-Up", :name => nil %>
		<% end %>
		<p>
			<span class="tips">Tips For Match-Up Charts</span><br/>
			<b>Chart #1</b>: Game-Qs for the 2015 season side-by-side. Click on “team”, “offense” or “defense” to change the comparison. <br />
			<b>Chart #2</b>: Season-Q values for team, offense and defense. Above zero: good.  below zero: bad. <br />
			<b>Chart #3</b>: View these two teams in relation to the other 30 teams. Season-Q values for team, offense and defense revealed the strongest teams in the league. Want a different view? Grab and move for a complete 3D look! Compare the two selected teams by marker size to see who has been hotter of late.
		</p>
	</div>
<% end %>

app/views/home/show.html.erb
<title>Game Maps | The Q5</title>
<p style="padding-top: 20px; width: 100%; height: 100%;"><%= image_tag(@stat.url) %></p>