config/routes.rb
Rails.application.routes.draw do

  root :to => 'splash#index'

	resources :portfolio, path: '/my-team/'
	resources :ranking, path: '/rankings/'
	
	resources :home, path: '/match-ups/'
	
	resources :stats, except: [:destroy] do
		collection { post :import }
		collection { delete :kill }
	end
	
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  def index
  	@teamNames = Stat.order(:team1).uniq.pluck(:team1, :short1)
  end

  def show
	@team1 = Stat.where("short1 = ?", params[:id]) 
	@team2 = @team1.pluck("team2")
	@teamNames = @team1.uniq.pluck("team1") 
	@team1wk = @team1.order("week").uniq.pluck("week")
	@year = Stat.pluck("year").last
	
	#return team1 data arrays by year
	@team1tmAll = @team1.pluck("win", "GameMean")	
	@team1offAll = @team1.pluck("win", "OFFGameMean")
	@team1defAll = @team1.pluck("win", "DEFGameMean")
	@team1s2dmAll = @team1.pluck("win", "Season2dateMean")

	@team1tm16 = @team1.where("year = ?", 2016).pluck("win", "GameMean") 	
	@team1off16 = @team1.where("year = ?", 2016).pluck("win", "OFFGameMean")
	@team1def16 = @team1.where("year = ?", 2016).pluck("win", "DEFGameMean")
	@team1s2dm16 = @team1.where("year = ?", 2016).pluck("win", "Season2dateMean")

	@team1tm15 = @team1.where("year = ?", 2015).pluck("win", "GameMean") 	
	@team1off15 = @team1.where("year = ?", 2015).pluck("win", "OFFGameMean")
	@team1def15 = @team1.where("year = ?", 2015).pluck("win", "DEFGameMean")
	@team1s2dm15 = @team1.where("year = ?", 2015).pluck("win", "Season2dateMean")

	@team1tm14 = @team1.where("year = ?", 2014).pluck("win", "GameMean")	
	@team1off14 = @team1.where("year = ?", 2014).pluck("win", "OFFGameMean")
	@team1def14 = @team1.where("year = ?", 2014).pluck("win", "DEFGameMean")
	@team1s2dm14 = @team1.where("year = ?", 2014).pluck("win", "Season2dateMean")
	
	@team1tm13 = @team1.where("year = ?", 2013).pluck("win", "GameMean")
	@team1off13 = @team1.where("year = ?", 2013).pluck("win", "OFFGameMean")
	@team1def13 = @team1.where("year = ?", 2013).pluck("win", "DEFGameMean")
	@team1s2dm13 = @team1.where("year = ?", 2013).pluck("win", "Season2dateMean")
	
	@team1tm12 = @team1.where("year = ?", 2012).pluck("win", "GameMean")	
	@team1off12 = @team1.where("year = ?", 2012).pluck("win", "OFFGameMean")
	@team1def12 = @team1.where("year = ?", 2012).pluck("win", "DEFGameMean")
	@team1s2dm12 = @team1.where("year = ?", 2012).pluck("win", "Season2dateMean")
	
	@team1tm11 = @team1.where("year = ?", 2011).pluck("win", "GameMean")	
	@team1off11 = @team1.where("year = ?", 2011).pluck("win", "OFFGameMean")
	@team1def11 = @team1.where("year = ?", 2011).pluck("win", "DEFGameMean")
	@team1s2dm11 = @team1.where("year = ?", 2011).pluck("win", "Season2dateMean")
				
	#team pt averages by year
		@w11 = @team1.where("year = ?", 2011).where("win = ?", 'W').average("team1pts")
		@l11 = @team1.where("year = ?", 2011).where("win = ?", 'L').average("team2pts")
	@teamPts2011 = ((@w11 + @l11)/2).round	
		@oppw11 = @team1.where("year = ?", 2011).where("win = ?", 'W').average("team2pts")
		@oppl11 = @team1.where("year = ?", 2011).where("win = ?", 'L').average("team1pts")
	@opponentPts2011 = ((@oppw11 + @oppl11)/2).round
	
		@w12 = @team1.where("year = ?", 2012).where("win = ?", 'W').average("team1pts")
		@l12 = @team1.where("year = ?", 2012).where("win = ?", 'L').average("team2pts")
	@teamPts2012 = ((@w12 + @l12)/2).round		
		@oppw12 = @team1.where("year = ?", 2012).where("win = ?", 'W').average("team2pts")
		@oppl12 = @team1.where("year = ?", 2012).where("win = ?", 'L').average("team1pts")
	@opponentPts2012 = ((@oppw12 + @oppl12)/2).round

		@w13 = @team1.where("year = ?", 2013).where("win = ?", 'W').average("team1pts")
		@l13 = @team1.where("year = ?", 2013).where("win = ?", 'L').average("team2pts")		
	@teamPts2013 = ((@w13 + @l13)/2).round
		@oppw13 = @team1.where("year = ?", 2013).where("win = ?", 'W').average("team2pts")
		@oppl13 = @team1.where("year = ?", 2013).where("win = ?", 'L').average("team1pts")
	@opponentPts2013 = ((@oppw13 + @oppl13)/2).round

		@w14 = @team1.where("year = ?", 2014).where("win = ?", 'W').average("team1pts")
		@l14 = @team1.where("year = ?", 2014).where("win = ?", 'L').average("team2pts")			
	@teamPts2014 = ((@w14 + @l14)/2).round
		@oppw14 = @team1.where("year = ?", 2014).where("win = ?", 'W').average("team2pts")
		@oppl14 = @team1.where("year = ?", 2014).where("win = ?", 'L').average("team1pts")
	@opponentPts2014 = ((@oppw14 + @oppl14)/2).round
	
		@w15 = @team1.where("year = ?", 2015).where("win = ?", 'W').pluck("team1pts")
		@l15 = @team1.where("year = ?", 2015).where("win = ?", 'L').pluck("team2pts")	
		@ptsFor15 = @w15 + @l15
	@teamPts2015 = (@ptsFor15.inject(0) { |sum, el| sum + el } / @ptsFor15.size)
		@oppw15 = @team1.where("year = ?", 2015).where("win = ?", 'W').pluck("team2pts")
		@oppl15 = @team1.where("year = ?", 2015).where("win = ?", 'L').pluck("team1pts")
		@ptsAgainst15 = @oppw15 + @oppl15
	@opponentPts2015 = (@ptsAgainst15.inject(0) { |add, ea| add + ea } / @ptsAgainst15.size)

	if @year == 2016
		@w16 = @team1.where("year = ?", 2016).where("win = ?", 'W').pluck("team1pts")
		@l16 = @team1.where("year = ?", 2016).where("win = ?", 'L').pluck("team2pts")	
		@ptsFor16 = @w16 + @l16
	@teamPts2016 = (@ptsFor16.inject(0) { |sum, el| sum + el } / @ptsFor16.size)
		@oppw16 = @team1.where("year = ?", 2016).where("win = ?", 'W').pluck("team2pts")
		@oppl16 = @team1.where("year = ?", 2016).where("win = ?", 'L').pluck("team1pts")
		@ptsAgainst16 = @oppw16 + @oppl16
	@opponentPts2016 = (@ptsAgainst16.inject(0) { |add, ea| add + ea } / @ptsAgainst16.size)
	end
	
	#league Off average
	@stat = Stat.all
		@leaguew11 = @stat.where("win = ?", 'W').where("year = ?", 2011).average("team1pts")
		@leaguel11 = @stat.where("win = ?", 'L').where("year = ?", 2011).average("team2pts")
	@leagueOPts2011 = ((@leaguew11 + @leaguel11)/2).round
	
		@leaguew12 = @stat.where("win = ?", 'W').where("year = ?", 2012).average("team1pts")
		@leaguel12 = @stat.where("win = ?", 'L').where("year = ?", 2012).average("team2pts")
	@leagueOPts2012 = ((@leaguew12 + @leaguel12)/2).round
	
		@leaguew13 = @stat.where("win = ?", 'W').where("year = ?", 2013).average("team1pts")
		@leaguel13 = @stat.where("win = ?", 'L').where("year = ?", 2013).average("team2pts")
	@leagueOPts2013 = ((@leaguew13 + @leaguel13)/2).round
	
		@leaguew14 = @stat.where("win = ?", 'W').where("year = ?", 2014).average("team1pts")
		@leaguel14 = @stat.where("win = ?", 'L').where("year = ?", 2014).average("team2pts")
	@leagueOPts2014 = ((@leaguew14 + @leaguel14)/2).round

		@leaguew15 = @stat.where("win = ?", 'W').where("year = ?", 2015).average("team1pts")
		@leaguel15 = @stat.where("win = ?", 'L').where("year = ?", 2015).average("team2pts")
	@leagueOPts2015 = ((@leaguew15 + @leaguel15)/2).round

	if @year == 2016
		@leaguew16 = @stat.where("win = ?", 'W').where("year = ?", 2016).average("team1pts")
		@leaguel16 = @stat.where("win = ?", 'L').where("year = ?", 2016).average("team2pts")
	@leagueOPts2016 = ((@leaguew16 + @leaguel16)/2).round
	
	end
	
	#record by year
	@win11 = @team1.where("win = ?", 'W').where("year = ?", 2011).count
	@loss11 = @team1.where("win = ?", 'L').where("year = ?", 2011).count

	@win12 = @team1.where("win = ?", 'W').where("year = ?", 2012).count
	@loss12 = @team1.where("win = ?", 'L').where("year = ?", 2012).count

	@win13 = @team1.where("win = ?", 'W').where("year = ?", 2013).count
	@loss13 = @team1.where("win = ?", 'L').where("year = ?", 2013).count

	@win14 = @team1.where("win = ?", 'W').where("year = ?", 2014).count
	@loss14 = @team1.where("win = ?", 'L').where("year = ?", 2014).count

	@win15 = @team1.where("win = ?", 'W').where("year = ?", 2015).count
	@loss15 = @team1.where("win = ?", 'L').where("year = ?", 2015).count	

	@win16 = @team1.where("win = ?", 'W').where("year = ?", 2016).count
	@loss16 = @team1.where("win = ?", 'L').where("year = ?", 2016).count	
	
	#score differences by win and loss
	@winValue16 = @team1.where("win = ?", 'W').where("year = ?", 2016).pluck("week", "diff")
	@lossValue16 = @team1.where("win = ?", 'L').where("year = ?", 2016).pluck("week", "diff")
	@winValue15 = @team1.where("win = ?", 'W').where("year = ?", 2015).pluck("week", "diff")
	@lossValue15 = @team1.where("win = ?", 'L').where("year = ?", 2015).pluck("week", "diff")
	@winValue14 = @team1.where("win = ?", 'W').where("year = ?", 2014).pluck("week", "diff")
	@lossValue14 = @team1.where("win = ?", 'L').where("year = ?", 2014).pluck("week", "diff")
	@winValue13 = @team1.where("win = ?", 'W').where("year = ?", 2013).pluck("week", "diff")
	@lossValue13 = @team1.where("win = ?", 'L').where("year = ?", 2013).pluck("week", "diff")
	@winValue12 = @team1.where("win = ?", 'W').where("year = ?", 2012).pluck("week", "diff")
	@lossValue12 = @team1.where("win = ?", 'L').where("year = ?", 2012).pluck("week", "diff")
	@winValue11 = @team1.where("win = ?", 'W').where("year = ?", 2011).pluck("week", "diff")
	@lossValue11 = @team1.where("win = ?", 'L').where("year = ?", 2011).pluck("week", "diff")

	#team schedule by season
	@record16 = @team1.where("year = ?", 2016).pluck("year", "week", "win", "team2", "team1pts", "team2pts", "id", "url")
	@record15 = @team1.where("year = ?", 2015).pluck("year", "week", "win", "team2", "team1pts", "team2pts", "id", "url")
	@record14 = @team1.where("year = ?", 2014).pluck("year", "week", "win", "team2", "team1pts", "team2pts", "id", "url")
	@record13 = @team1.where("year = ?", 2013).pluck("year", "week", "win", "team2", "team1pts", "team2pts", "id", "url")
	@record12 = @team1.where("year = ?", 2012).pluck("year", "week", "win", "team2", "team1pts", "team2pts", "id", "url")
	@record11 = @team1.where("year = ?", 2011).pluck("year", "week", "win", "team2", "team1pts", "team2pts", "id", "url")
  end
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/views/portfolio/_diffScript.html.erb
<script type="text/javascript">
	$(function () {
		var winArray16 = <%= raw @winValue16.to_json %>
		var lossArray16 = <%= raw @lossValue16.to_json %>
		var winArray15 = <%= raw @winValue15.to_json %>
		var lossArray15 = <%= raw @lossValue15.to_json %>
		var winArray14 = <%= raw @winValue14.to_json %>
		var lossArray14 = <%= raw @lossValue14.to_json %>
		var winArray13 = <%= raw @winValue13.to_json %>
		var lossArray13 = <%= raw @lossValue13.to_json %>
		var winArray12 = <%= raw @winValue12.to_json %>
		var lossArray12 = <%= raw @lossValue12.to_json %>
		var winArray11 = <%= raw @winValue11.to_json %>
		var lossArray11 = <%= raw @lossValue11.to_json %>
		var chart = new Highcharts.Chart({
		chart: {
			renderTo: 'diff',
			type: 'scatter',
			fontSize:'100%',
			backgroundColor:'rgba(255, 255, 255, 0.1)'
		},
		title: {
			text: '',
			style: {
				fontSize:'2vmax'
			}
		},
		subtitle: {
			text: 'Win vs Loss PT Differential By Week (2016)',
			style: {
				fontSize:'1.7vmax'
			}
		},
		xAxis: {
			categories: [''],
			title: {
				style: {
                    fontSize:'1.7vmax',
                }
			}
		},
		yAxis: {
		    min: 0,
            max: 50,
            tickInterval: 5,
            lineWidth: 1,
			title: {
				text: 'Points',
				style: {
                    fontSize:'1.7vmax',
                }
			}
		},
		tooltip: {
			formatter: function() {
				return '<i>' + this.series.name + '</i>' + ' by ' + '<b>' + this.y + '</b>';
			}
		},
		plotOptions: {
			series: {
                marker: {
                    radius: 8
                }
            },
			line: {
				dataLabels: {
					enabled: false,
				},
				enableMouseTracking: true
			}
		},
		series: [{
			name: 'WIN',
			color: '#006E29',
			data: winArray16,
			marker: {
                symbol: 'triangle'
            },
		}, {
			name: 'LOSS',
			color: '#333333',
			data: lossArray16,
			marker: {
                symbol: 'triangle-down'
            },
		}]
	});
		$(".difference").change(function() {
			var value = this.getAttribute("value");

			if (value == 'f') 
			{
				chart.series[0].remove();
				chart.series[0].remove();
				chart.setTitle({ 
					text: '' 
					}, 
					{ 
					text: 'Win vs Loss PT Differential By Week (2016)'
				});
				chart.addSeries({
					name: 'WIN',
					type: 'scatter',
					color: '#006E29',  
				    data: winArray16,
					marker: {
						symbol: 'triangle'
					},            
				});   
				chart.addSeries({
					name: 'LOSS',
					type: 'scatter',
					color: '#333333',  
				    data: lossArray16,
					marker: {
						symbol: 'triangle-down'
					},            
				});               
			}
			
			else if (value == 'a') 
			{
				chart.series[0].remove();
				chart.series[0].remove();
				chart.setTitle({ 
					text: '' 
					}, 
					{ 
					text: 'Win vs Loss PT Differential By Week (2014)'
				});
				chart.addSeries({
					name: 'WIN',
					type: 'scatter',
					color: '#006E29',  
				    data: winArray14,
					marker: {
						symbol: 'triangle'
					},            
				});   
				chart.addSeries({
					name: 'LOSS',
					type: 'scatter',
					color: '#333333',  
				    data: lossArray14,
					marker: {
						symbol: 'triangle-down'
					},            
				});               
			}


			else if (value == 'b') 
			{
				chart.series[0].remove();
				chart.series[0].remove();
				chart.setTitle({ 
					text: '' 
					}, 
					{ 
					text: 'Win vs Loss PT Differential By Week (2013)'
				});
				chart.addSeries({
					name: 'WIN',
					type: 'scatter',
					color: '#006E29',  
				    data: winArray13,
					marker: {
						symbol: 'triangle'
					},            
				});                 
				chart.addSeries({
					name: 'LOSS',
					type: 'scatter',
					color: '#333333',  
				    data: lossArray13,
					marker: {
						symbol: 'triangle-down'
					},            
				});               
			}
			
			else if (value == 'c') 
			{
				chart.series[0].remove();
				chart.series[0].remove();
				chart.setTitle({ 
					text: '' 
					}, 
					{ 
					text: 'Win vs Loss PT Differential By Week (2012)'
				});
				chart.addSeries({
					name: 'WIN',
					type: 'scatter',
					color: '#006E29',  
				    data: winArray12,
					marker: {
						symbol: 'triangle'
					},            
				});              
				chart.addSeries({
					name: 'LOSS',
					type: 'scatter',
					color: '#333333',  
				    data: lossArray12,
					marker: {
						symbol: 'triangle-down'
					},            
				});           
			}
			
			else if (value == 'd') 
			{
				chart.series[0].remove();
				chart.series[0].remove();
				chart.setTitle({ 
					text: '' 
					}, 
					{ 
					text: 'Win vs Loss PT Differential By Week (2011)'
				});
				chart.addSeries({
					name: 'WIN',
					type: 'scatter',
					color: '#006E29',  
				    data: winArray11,
					marker: {
						symbol: 'triangle'
					},            
				});               
				chart.addSeries({
					name: 'LOSS',
					type: 'scatter',
					color: '#333333',  
				    data: lossArray11,
					marker: {
						symbol: 'triangle-down'
					},            
				});             
			}
			
			else if (value == 'e') 
			{
				chart.series[0].remove();
				chart.series[0].remove();
				chart.setTitle({ 
					text: '' 
					}, 
					{ 
					text: 'Win vs Loss PT Differential By Week (2015)'
				});
				chart.addSeries({
					name: 'WIN',
					type: 'scatter',
					color: '#006E29',  
				    data: winArray15,
					marker: {
						symbol: 'triangle'
					},            
				});               
				chart.addSeries({
					name: 'LOSS',
					type: 'scatter',
					color: '#333333',  
				    data: lossArray15,
					marker: {
						symbol: 'triangle-down'
					},            
				});             
			}
			else {
			   alert("Error!");   
			}
		});
	});
</script>

app/views/portfolio/_scheduleTable.html.erb
<div id="schedule">
	<button onclick="show16();return false"/>2016</button>
	<button onclick="show15();return false"/>2015</button>
	<button onclick="show14();return false"/>2014</button>
	<button onclick="show13();return false"/>2013</button>
	<button onclick="show12();return false"/>2012</button>
	<button onclick="show11();return false"/>2011</button>
	<div id="teamTable15" style="display:none">	
		<table cellspacing='0'> 
			<thead>
				<tr>
					<th colspan="3">2015 Schedule (<%= @win15 %>-<%= @loss15 %>)</th>
				</tr>
			</thead>
			<tbody>
				<% @record15.each do |r15| %>
					<% if r15[5].nil? %>
					<tr>
						<td><i>Wk <%= r15[1] %></i>:</td>
						<td ><b><%= r15[2] %></b></td>
						<td></td>
					</tr>	
					<% else %>
					<tr>
						<td><i>Wk <%= r15[1] %></i>:</td>	
						<td><b><%= r15[2] %></b> <%= r15[4] %>-<%= r15[5] %> vs <%= r15[3] %></td>
						<td><%= link_to 'Game Map', home_path(:id => r15[6]) %></td>
					</tr>					
					<% end %>
				<% end %>
			</tbody>
		</table>
	</div>
	<div id="teamTable14" style="display:none">	
		<table cellspacing='0'> 
			<thead>
				<tr>
					<th colspan="3">2014 Schedule (<%= @win14 %>-<%= @loss14 %>)</th>
				</tr>
			</thead>
			<tbody>
				<% @record14.each do |r14| %>
					<% if r14[5].nil? %>
					<tr>
						<td><i>Wk <%= r14[1] %></i>:</td>
						<td ><b><%= r14[2] %></b></td>
						<td></td>
					</tr>	
					<% else %>
					<tr>
						<td><i>Wk <%= r14[1] %></i>:</td>	
						<td><b><%= r14[2] %></b> <%= r14[4] %>-<%= r14[5] %> vs <%= r14[3] %></td>
						<td><%= link_to 'Game Map', home_path(:id => r14[6]) %></td>
					</tr>					
					<% end %>
				<% end %>
			</tbody>
		</table>
	</div>
	<div id="teamTable13" style="display:none">	
		<table cellspacing='0'> 
			<thead>
				<tr>
					<th colspan="3">2013 Schedule (<%= @win13 %>-<%= @loss13 %>)</th>
				</tr>
			</thead>
			<tbody>
				<% @record13.each do |r13| %>
					<% if r13[5].nil? %>
					<tr>
						<td><i>Wk <%= r13[1] %></i>:</td>
						<td ><b><%= r13[2] %></b></td>
						<td></td>
					</tr>	
					<% else %>
					<tr>
						<td><i>Wk <%= r13[1] %></i>:</td>	
						<td><b><%= r13[2] %></b> <%= r13[4] %>-<%= r13[5] %> vs <%= r13[3] %></td>
						<td><%= link_to 'Game Map', home_path(:id => r13[6]) %></td>
					</tr>					
					<% end %>
				<% end %>
			</tbody>
		</table>
	</div>
	<div id="teamTable12" style="display:none">	
		<table cellspacing='0'> 
			<thead>
				<tr>
					<th colspan="3">2012 Schedule (<%= @win12 %>-<%= @loss12 %>)</th>
				</tr>
			</thead>
			<tbody>
				<% @record12.each do |r12| %>
					<% if r12[5].nil? %>
					<tr>
						<td><i>Wk <%= r12[1] %></i>:</td>
						<td ><b><%= r12[2] %></b></td>
						<td></td>
					</tr>	
					<% else %>
					<tr>
						<td><i>Wk <%= r12[1] %></i>:</td>	
						<td><b><%= r12[2] %></b> <%= r12[4] %>-<%= r12[5] %> vs <%= r12[3] %></td>
						<td><%= link_to 'Game Map', home_path(:id => r12[6]) %></td>
					</tr>					
					<% end %>
				<% end %>
			</tbody>
		</table>
	</div>
	<div id="teamTable11" style="display:none">	
		<table cellspacing='0'> 
			<thead>
				<tr>
					<th colspan="3">2011 Schedule (<%= @win11 %>-<%= @loss11 %>)</th>
				</tr>
			</thead>
			<tbody>
				<% @record11.each do |r11| %>
					<% if r11[5].nil? %>
					<tr>
						<td><i>Wk <%= r11[1] %></i>:</td>
						<td ><b><%= r11[2] %></b></td>
						<td></td>
					</tr>	
					<% else %>
					<tr>
						<td><i>Wk <%= r11[1] %></i>:</td>	
						<td><b><%= r11[2] %></b> <%= r11[4] %>-<%= r11[5] %> vs <%= r11[3] %></td>
						<td><%= link_to 'Game Map', home_path(:id => r11[6]) %></td>
					</tr>					
					<% end %>
				<% end %>
			</tbody>
		</table>
	</div>
	<div id="teamTable16" style="display:block">	
		<table cellspacing='0'> 
			<thead>
				<tr>
					<th colspan="3">2016 Schedule (<%= @win16 %>-<%= @loss16 %>)</th>
				</tr>
			</thead>
			<tbody>
				<% @record16.each do |r16| %>
					<% if r16[5].nil? %>
					<tr>
						<td><i>Wk <%= r16[1] %></i>:</td>
						<td><b><%= r16[2] %></b></td>
						<td></td>
					</tr>	
					<% else %>
					<tr>
						<td><i>Wk <%= r16[1] %></i>:</td>	
						<td><b><%= r16[2] %></b> <%= r16[4] %>-<%= r16[5] %> vs <%= r16[3] %></td>
						<td><%= link_to 'Game Map', home_path(:id => r16[6]) %></td>
					</tr>					
					<% end %>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

<script> 
	function show16() { 
	document.getElementById("teamTable16").style.display="block"; 
	document.getElementById("teamTable15").style.display="none"; 
	document.getElementById("teamTable14").style.display="none"; 
	document.getElementById("teamTable13").style.display="none"; 
	document.getElementById("teamTable12").style.display="none"; 
	document.getElementById("teamTable11").style.display="none"; 
	} 
	function show15() { 
	document.getElementById("teamTable16").style.display="none"; 
	document.getElementById("teamTable15").style.display="block"; 
	document.getElementById("teamTable14").style.display="none"; 
	document.getElementById("teamTable13").style.display="none"; 
	document.getElementById("teamTable12").style.display="none"; 
	document.getElementById("teamTable11").style.display="none"; 
	} 
	function show14() {
	document.getElementById("teamTable16").style.display="none"; 
	document.getElementById("teamTable15").style.display="none";
	document.getElementById("teamTable14").style.display="block"; 
	document.getElementById("teamTable13").style.display="none"; 
	document.getElementById("teamTable12").style.display="none"; 
	document.getElementById("teamTable11").style.display="none"; 
	} 
	function show13() { 
	document.getElementById("teamTable16").style.display="none"; 
	document.getElementById("teamTable15").style.display="none";
	document.getElementById("teamTable14").style.display="none"; 
	document.getElementById("teamTable13").style.display="block"; 
	document.getElementById("teamTable12").style.display="none"; 
	document.getElementById("teamTable11").style.display="none"; 
	} 
	function show12() { 
	document.getElementById("teamTable16").style.display="none"; 
	document.getElementById("teamTable15").style.display="none";
	document.getElementById("teamTable14").style.display="none"; 
	document.getElementById("teamTable13").style.display="none"; 
	document.getElementById("teamTable12").style.display="block"; 
	document.getElementById("teamTable11").style.display="none"; 
	} 
	function show11() { 
	document.getElementById("teamTable16").style.display="none"; 
	document.getElementById("teamTable15").style.display="none";
	document.getElementById("teamTable14").style.display="none"; 
	document.getElementById("teamTable13").style.display="none"; 
	document.getElementById("teamTable12").style.display="none"; 
	document.getElementById("teamTable11").style.display="block"; 
	} 
</script>

app/views/portfolio/index.html.erb
<title>Portfolio | The Q5</title>
<div class="x-container max width">
	<div class="x-landmark-breadcrumbs-wrap">
		<div class="x-landmark">
			<h1 class="h-landmark entry-title"><span>My Team</span></h1>
			<%= link_to root_path do %><p><i>Want to Learn More About This Tool?</i></p><% end %>
		</div>
	</div>
</div>

<div id="teamPortfolio">
	<div id="indy_team">
	<% @teamNames.each do |tn| %>
		<p class="team_name"><%= link_to tn[0], portfolio_path(:id => tn[1]) %></p>
	<% end %>
	</div>
</div>