config/routes.rb
Rails.application.routes.draw do

  root :to => 'splash#index'

	resources :portfolio, path: '/my-team/'
	resources :ranking, path: '/rankings/'
	
	resources :home, path: '/match-ups/'
	
	resources :stats, except: [:destroy] do
		collection { post :import }
		collection { delete :kill }
	end
	
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'highcharts' %>
  <%= javascript_include_tag 'highcharts-3d' %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>		
<meta property="og:site_name" content="The Q5"><meta property="og:title" content="Match-Ups"><meta property="og:description" content="Game Day Preparation – How Do Teams Match Up? Ready to see how your team matches up? Using team, offense and defense performance from the entire season-to-date, any two teams can be compared side-by-side. Unlock&hellip;"><meta property="og:image" content=""><meta property="og:url" content="http://theqfive.com/match-ups/"><meta property="og:type" content="article">
</head>
<body>
<header class="masthead masthead-inline" role="banner">
    
<div class="x-navbar-wrap">
	<div class="x-navbar">
  		<div class="x-navbar-inner">
			<div class="x-container max width">
          		<a href="http://theq5.com/" class="x-brand img" title="Graphical Football Analytics">
  					<%= image_tag("TheQ5-logo_Primary-RGB-Color-crop-263x241.png", alt: "Graphical Football Analytics") %>
  				</a>          
			<nav class="x-nav-wrap desktop" role="navigation">
  				<ul id="menu-main-navigation" class="x-nav" style="margin: 55px 0 -55px 0; font-size: 16px;">
  					<li id="menu-item-91" class="menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children menu-item-91">
						<%= link_to 'The Q5 Zone', root_path %></li>
					</li>
						<li id="menu-item-82" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-82"><%= link_to 'Match-Ups', home_index_path %></li>
						<li id="menu-item-81" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-81"><%= link_to 'My Team', portfolio_index_path, 'data-no-turbolink' => true %></li>
						<li id="menu-item-87" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-87"><%= link_to 'Rankings', ranking_index_path, 'data-no-turbolink' => true %></li>
						<li id="menu-item-86" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-86"><a href="http://theq5.com/"><span>Home</span></a></li>
					</li>
				</ul>
			</nav>    
			<nav class="x-nav-wrap mobile" role="navigation">
  				<ul id="menu-main-navigation" class="x-nav" style="font-size: 16px;">
  					<li id="menu-item-91" class="menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children menu-item-91">
						<%= link_to 'The Q5 Zone', root_path %></li>
					</li>
						<li id="menu-item-82" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-82"><%= link_to 'Match-Ups', home_index_path %></li>
						<li id="menu-item-81" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-81"><%= link_to 'My Team', portfolio_index_path, 'data-no-turbolink' => true %></li>
						<li id="menu-item-87" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-87"><%= link_to 'Rankings', ranking_index_path, 'data-no-turbolink' => true %></li>
					</li>
				</ul>
			</nav> 
		</div>
	</div>
</div>
</header>

<header class="x-header-landmark">
	<div class="x-container max width">
		<div class="x-landmark-breadcrumbs-wrap">
			<div class="x-landmark">
				<h1 class="q5zone"><%= link_to image_tag("q5zone.png"), root_path %></h1>
			</div>
		</div>
	</div>
	<%= yield %>
</header>
<div class="x-container max width offset"></div>
<div class="x-widgetbar collapse">
	<div class="x-widgetbar-inner">
		<div class="x-container max width">
		</div>
	</div>
  </div>
</div>

<a class="x-scroll-top  fade" href="#top" title="Back to Top">
	<i class="x-icon-angle-up" data-x-icon="&#xf106;"></i>
</a>


<footer class="x-colophon bottom" role="contentinfo" style="background-color: #333;">
	<div class="x-container max width">
        <ul id="menu-footer-navigation" class="x-nav"><li id="menu-item-99" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-99"><a href="http://theq5.com/faq/">FAQ</a></li>
			<li id="menu-item-106" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-106"><a href="http://theq5.com/giving-back/">Giving Back</a></li>
			<li id="menu-item-110" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-110"><a href="http://theq5.com/events/">Events</a></li>
			<li id="menu-item-107" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-107"><a href="http://theq5.com/privacy-policy/">Privacy Policy</a></li>
			<li id="menu-item-100" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-100"><a href="http://theq5.com/terms-of-use/">Terms of Use</a></li>
		</ul>        
        <div class="x-colophon-content">
        	<p>The Q5 &copy 2015 | 866.640.3484 | <a href="mailto:contact@theq5.com">contact@theq5.com</a> | San Luis Obispo, CA</p>          
    	</div>
    </div>
</footer>

</body>
</html>